name: mhu_catalog
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependency_overrides:
  mhu_dart_commons:
    path: ../mhu_dart_commons
  #  mhu_dart_proto:
  #    path: ../mhu_dart_proto
  #  mhu_dart_builder:
  #    path: ../mhu_dart_builder
  #  mhu_dart_model:
  #    path: ../mhu_dart_model
  mhu_flutter_commons:
    path: ../mhu_flutter_commons

dependencies:
  flutter:
    sdk: flutter

  mhu_dart_commons: ^1.0.8
  mhu_flutter_commons: ^1.0.5

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.12
  collection: ^1.17.1
  recase: ^4.1.0
  flutter_svg: any
  go_router: ^10.0.0
  flutter_markdown: ^0.6.17
  flutter_native_splash: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^2.4.1

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/descriptions/
    - assets/images/

mhu:
  title: MHU Catalog
  short_title: MHU Catalog
  icon: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/apps/default/48px.svg

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
